# Generated by Django 5.0.6 on 2024-11-17 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
